import json
from app.models.task import Task
from app.llm.client import call_llm
from app.llm.prompts.task_prompts import TASK_GENERATION_SYSTEM_PROMPT


class GenerativeTaskGenerator:
    """
    Pure AI-generative task generator.
    No datasets required - AI creates everything based on student profile.
    """

    def generate_task(self, user_profile: dict) -> Task:
        """
        Generate a task using the LLM based on the student's profile.

        Args:
            user_profile: dict containing level, error_profile, recent_tasks, etc.

        Returns:
            A Task object generated by the LLM.
        """
        generation_prompt = self._build_generation_prompt(user_profile)

        try:
            response = call_llm(
                generation_prompt,
                system_prompt=TASK_GENERATION_SYSTEM_PROMPT,
                expect_json=True
            )
            task_data = json.loads(response)
        except (json.JSONDecodeError, ValueError):
            # Fallback to a simple task if parsing fails
            task_data = {
                "task_type": "word_translation",
                "instruction": "Terjemahkan kata berikut ke bahasa Inggris: 'berlari'",
                "expected_answer": "run",
                "acceptable_answers": ["jog"],
                "metadata": {}
            }

        task_type = task_data.get("task_type", "word_translation")
        instruction = task_data.get("instruction", "")
        expected_answer = task_data.get("expected_answer")
        acceptable_answers = task_data.get("acceptable_answers", [])
        metadata = task_data.get("metadata", {})

        return Task(
            task_type=task_type,
            instruction=instruction,
            level=user_profile.get("level", 1),
            expected_answer=expected_answer,
            acceptable_answers=acceptable_answers,
            metadata=metadata
        )

    def _build_generation_prompt(self, profile: dict) -> str:
        """
        Build a detailed prompt for the LLM to generate an appropriate task.
        """
        weak_areas = self._analyze_weak_areas(profile.get("error_profile", {}))
        recent_tasks = profile.get("recent_tasks", [])

        return f"""
Generate a personalized English language production task for an Indonesian learner.

## Student Profile

**Level:** {profile.get('level', 1)} out of 10
**Total Tasks Completed:** {profile.get('total_tasks', 0)}
**Success Rate:** {profile.get('success_rate', 0):.1%}
**Average Grammar Score:** {profile.get('avg_grammar_score', 0):.1f}/5
**Average Vocabulary Score:** {profile.get('avg_vocabulary_score', 0):.1f}/5

## Weak Areas (FOCUS HERE!)

{weak_areas}

## Recent Tasks (avoid repetition)

{self._format_recent_tasks(recent_tasks)}

## Task Requirements

1. **Instruction Language:** Indonesian (clear and natural)
2. **Expected Answer:** English
3. **Difficulty Target:** Should result in ~70% success rate for this student
4. **Focus:** Target the student's weakest areas
5. **Variety:** Don't repeat recent task patterns

## Task Type Selection by Level:

- **Level 1-3:** word_translation, phrase_translation
- **Level 3-6:** sentence_translation, constrained_production
- **Level 7-10:** context_production, paragraph_production

Generate the task now. Return only valid JSON.
"""

    def _analyze_weak_areas(self, error_profile: dict) -> str:
        """
        Format the error profile into a readable weak-areas description.
        """
        if not error_profile:
            return "No specific weak areas identified yet. Start with basic tasks."

        sorted_errors = sorted(
            error_profile.items(),
            key=lambda x: x[1],
            reverse=True
        )

        weak_areas = []
        for error_type, error_rate in sorted_errors[:5]:
            severity = "CRITICAL" if error_rate > 0.5 else "MODERATE" if error_rate > 0.3 else "MINOR"
            weak_areas.append(
                f"- {error_type}: {error_rate:.1%} error rate [{severity}]"
            )

        return "\n".join(weak_areas) if weak_areas else "No major weaknesses yet."

    def _format_recent_tasks(self, recent_tasks: list) -> str:
        """
        Format recent tasks to help the AI avoid repetition.
        """
        if not recent_tasks:
            return "No recent tasks."

        formatted = []
        for i, task in enumerate(recent_tasks[-5:], 1):
            instruction_preview = task.get("instruction", "")[:80]
            formatted.append(
                f"{i}. [{task.get('task_type')}] {instruction_preview}..."
            )

        return "\n".join(formatted)


# Keep backward-compatible alias so existing imports still work
class TaskGenerator(GenerativeTaskGenerator):
    """
    Backward-compatible wrapper around GenerativeTaskGenerator.
    Accepts the same constructor arguments as the old dataset-based generator
    but delegates to the AI-generative approach.
    """

    def __init__(self, level: int = 1, error_profile: dict = None):
        self._level = level
        self._error_profile = error_profile or {}

    def generate(self) -> Task:
        """
        Generate a task using the student's level and error profile.
        """
        profile = {
            "level": self._level,
            "total_tasks": 0,
            "success_rate": 0.0,
            "avg_grammar_score": 0.0,
            "avg_vocabulary_score": 0.0,
            "error_profile": self._error_profile,
            "recent_tasks": []
        }
        return self.generate_task(profile)
